In [1]:
import numpy as np
import pandas as pd
import matplotlib
%matplotlib inline
from scipy import stats
import seaborn as sns
import matplotlib.pyplot as plt

from beakerx import *
from beakerx.object import beakerx

# Total Population per Country

In [9]:
tot_pop_df = pd.read_csv('data_sets/csv/tot_pop_yr.csv')

tot_pop_df.head()

In [6]:
tot_pop_df_long = pd.melt(tot_pop_df,
                          id_vars = 'country')

In [7]:
tot_pop_df_long

            country variable       value
0             Aruba     1980     60096.0
1       Afghanistan     1980  13356511.0
2            Angola     1980   8341289.0
3           Albania     1980   2671997.0
4           Andorra     1980     36067.0
...             ...      ...         ...
10291        Kosovo     2018   1845300.0
10292   Yemen, Rep.     2018  28498687.0
10293  South Africa     2018  57779622.0
10294        Zambia     2018  17351822.0
10295      Zimbabwe     2018  14439018.0

[10296 rows x 3 columns]

In [8]:
tot_pop_long_df = pd.melt(tot_pop_df,
                          id_vars = 'country',
                          var_name = 'year',
                          value_name = 'population')

In [18]:
tot_pop_df_tidy = tot_pop_long_df.sort_values(by = ['country', 'year'])

In [19]:
tot_pop_df_tidy.to_csv('')

           country  year  population
1      Afghanistan  1980  13356511.0
265    Afghanistan  1981  13171673.0
529    Afghanistan  1982  12882528.0
793    Afghanistan  1983  12537730.0
1057   Afghanistan  1984  12204292.0
...            ...   ...         ...
9239      Zimbabwe  2014  13586681.0
9503      Zimbabwe  2015  13814629.0
9767      Zimbabwe  2016  14030390.0
10031     Zimbabwe  2017  14236745.0
10295     Zimbabwe  2018  14439018.0

[10296 rows x 3 columns]

In [5]:
world_tot_pop_df = pd.read_csv('data_sets/csv/tot_pop_world_yr.csv')

       Unnamed: 0      country  year  population
0               1  Afghanistan  1980  13356511.0
1             265  Afghanistan  1981  13171673.0
2             529  Afghanistan  1982  12882528.0
3             793  Afghanistan  1983  12537730.0
4            1057  Afghanistan  1984  12204292.0
...           ...          ...   ...         ...
10291        9239     Zimbabwe  2014  13586681.0
10292        9503     Zimbabwe  2015  13814629.0
10293        9767     Zimbabwe  2016  14030390.0
10294       10031     Zimbabwe  2017  14236745.0
10295       10295     Zimbabwe  2018  14439018.0

[10296 rows x 4 columns]

In [8]:
world_tot_pop_df.columns

Index(['Unnamed: 0', 'country', 'year', 'population'], dtype='object')

In [12]:
drop = world_tot_pop_df.drop(columns = 'Unnamed: 0')

In [19]:
drop.to_csv('data_sets/csv/tot_pop_world_yr.csv')

# Pertussis cases

In [5]:
pertussis_cases_df = pd.read_csv('data_sets/csv/pertussis_cases.csv')

pertussis_cases_df.head()

,country,disease,2018,2017,2016,2015,2014,2013,2012,2011,...,1989,1988,1987,1986,1985,1984,1983,1982,1981,1980
0,Afghanistan,pertussis,488.0,1.0,0.0,432.0,0.0,371.0,1497.0,0.0,...,1494.0,4587.0,6073.0,5872.0,8531.0,6175.0,10209.0,8528.0,15388.0,15748.0
1,Albania,pertussis,19.0,7.0,43.0,NaN,NaN,6.0,16.0,4.0,...,302.0,508.0,112.0,115.0,172.0,89.0,126.0,312.0,280.0,137.0
2,Algeria,pertussis,17.0,6.0,2.0,0.0,0.0,69.0,104.0,1.0,...,32.0,45.0,69.0,24.0,520.0,894.0,395.0,663.0,967.0,710.0
3,Andorra,pertussis,2.0,0.0,3.0,16.0,1.0,6.0,3.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,pertussis,0.0,NaN,0.0,0.0,0.0,0.0,1259.0,1554.0,...,21674.0,14343.0,10015.0,6953.0,15846.0,23993.0,28461.0,31429.0,31481.0,54126.0

In [6]:
tidy = pd.melt(pertussis_cases_df,
               id_vars = ['country', 'disease'])

In [7]:
tidy.head()

       country    disease variable  value
0  Afghanistan  pertussis     2018  488.0
1      Albania  pertussis     2018   19.0
2      Algeria  pertussis     2018   17.0
3      Andorra  pertussis     2018    2.0
4       Angola  pertussis     2018    0.0

In [8]:
tidy2 = pd.melt(pertussis_cases_df,
                id_vars = ['country', 'disease'],
                var_name = 'year',
                value_name = 'cases')

tidy2.head()

       country    disease  year  cases
0  Afghanistan  pertussis  2018  488.0
1      Albania  pertussis  2018   19.0
2      Algeria  pertussis  2018   17.0
3      Andorra  pertussis  2018    2.0
4       Angola  pertussis  2018    0.0

In [9]:
tidy3 = tidy2.sort_values(by = ['country', 'year'])

tidy3.head()

          country    disease  year    cases
7372  Afghanistan  pertussis  1980  15748.0
7178  Afghanistan  pertussis  1981  15388.0
6984  Afghanistan  pertussis  1982   8528.0
6790  Afghanistan  pertussis  1983  10209.0
6596  Afghanistan  pertussis  1984   6175.0

In [11]:
tidy3.to_csv('data_sets/csv/pertussis_cases.csv')

In [15]:
pertussis_cases_df = pd.read_csv('data_sets/csv/pertussis_cases.csv')

pertussis_cases_df

          country    disease  year    cases
0     Afghanistan  pertussis  1980  15748.0
1     Afghanistan  pertussis  1981  15388.0
2     Afghanistan  pertussis  1982   8528.0
3     Afghanistan  pertussis  1983  10209.0
4     Afghanistan  pertussis  1984   6175.0
...           ...        ...   ...      ...
7561     Zimbabwe  pertussis  2014      0.0
7562     Zimbabwe  pertussis  2015      0.0
7563     Zimbabwe  pertussis  2016      3.0
7564     Zimbabwe  pertussis  2017      0.0
7565     Zimbabwe  pertussis  2018      0.0

[7566 rows x 4 columns]

# Measles Cases

In [25]:
measles_cases_df = pd.read_csv('data_sets/csv/measles_cases.csv')

measles_cases_df.head()

,country,disease,2018,2017,2016,2015,2014,2013,2012,2011,...,1989,1988,1987,1986,1985,1984,1983,1982,1981,1980
0,Afghanistan,measles,2012.0,1511.0,638.0,1154.0,492.0,430.0,2787.0,3013.0,...,1170.0,4561.0,10357.0,8107.0,14457.0,16199.0,18808.0,20320.0,31107.0,32455.0
1,Albania,measles,1469.0,12.0,17.0,NaN,NaN,0.0,9.0,28.0,...,136034.0,0.0,0.0,0.0,0.0,0.0,17.0,3.0,NaN,NaN
2,Algeria,measles,3356.0,112.0,41.0,63.0,0.0,25.0,18.0,112.0,...,4169.0,2634.0,2500.0,3975.0,20114.0,22553.0,22126.0,29584.0,20849.0,15527.0
3,Andorra,measles,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,measles,57.0,29.0,53.0,119.0,11699.0,8523.0,4458.0,1449.0,...,19820.0,21009.0,13368.0,15580.0,22822.0,22685.0,22589.0,30067.0,19714.0,29656.0

In [33]:
measles1 = pd.melt(measles_cases_df,
               id_vars = ['country', 'disease'])

measles1.head()

measles1.to_csv('data_sets/csv/measles_cases1.csv')

In [31]:
measles2 = pd.melt(measles1,
                id_vars = ['country', 'disease'],
                value_name = 'cases')

measles2.head()

       country  disease  variable cases
0  Afghanistan  measles  variable  2018
1      Albania  measles  variable  2018
2      Algeria  measles  variable  2018
3      Andorra  measles  variable  2018
4       Angola  measles  variable  2018

In [34]:
measles_df = pd.read_csv('data_sets/csv/measles_cases1.csv')

measles_df.head()

       country  disease  year   cases
0  Afghanistan  measles  2018  2012.0
1      Albania  measles  2018  1469.0
2      Algeria  measles  2018  3356.0
3      Andorra  measles  2018     0.0
4       Angola  measles  2018    57.0

In [35]:
measles_df_sorted = measles_df.sort_values(by = ['country', 'year'])

measles_df_sorted.head()

          country  disease  year    cases
7372  Afghanistan  measles  1980  32455.0
7178  Afghanistan  measles  1981  31107.0
6984  Afghanistan  measles  1982  20320.0
6790  Afghanistan  measles  1983  18808.0
6596  Afghanistan  measles  1984  16199.0

In [36]:
measles_df_sorted.to_csv('data_sets/csv/measles_cases.csv')

In [37]:
measles_df = pd.read_csv('data_sets/csv/measles_cases.csv')

measles_df.head()

       country  disease  year    cases
0  Afghanistan  measles  1980  32455.0
1  Afghanistan  measles  1981  31107.0
2  Afghanistan  measles  1982  20320.0
3  Afghanistan  measles  1983  18808.0
4  Afghanistan  measles  1984  16199.0

# Mumps

In [46]:
mumps = pd.read_csv('data_sets/csv/mumps_cases.csv')

mumps.head()

       country disease  year  cases
0  Afghanistan   Mumps  2018    NaN
1      Albania   Mumps  2018   13.0
2      Algeria   Mumps  2018    NaN
3      Andorra   Mumps  2018   31.0
4       Angola   Mumps  2018    NaN

In [48]:
mumps2 = mumps.sort_values(by = ['country', 'year'])

mumps2.head()

          country disease  year  cases
3667  Afghanistan   Mumps  1999    NaN
3474  Afghanistan   Mumps  2000    NaN
3281  Afghanistan   Mumps  2001    NaN
3088  Afghanistan   Mumps  2002    NaN
2895  Afghanistan   Mumps  2003    NaN

In [49]:
mumps2.to_csv('data_sets/csv/mumps_cases.csv')

In [50]:
mumps = pd.read_csv('data_sets/csv/mumps_cases.csv')

mumps.head()

       country disease  year  cases
0  Afghanistan   Mumps  1999    NaN
1  Afghanistan   Mumps  2000    NaN
2  Afghanistan   Mumps  2001    NaN
3  Afghanistan   Mumps  2002    NaN
4  Afghanistan   Mumps  2003    NaN

# DTP1 Coverage

In [52]:
dtp1_df = pd.read_csv('data_sets/csv/dtp1_pertussis_coverage.csv')

dtp1_df.head()

,country,vaccine,2018,2017,2016,2015,2014,2013,2012,2011,...,1989,1988,1987,1986,1985,1984,1983,1982,1981,1980
0,Afghanistan,DTP1,73,73,73,73,73,76,78,78,...,58.0,60.0,50.0,32.0,37.0,39.0,24.0,24.0,NaN,22.0
1,Albania,DTP1,99,99,99,99,99,99,99,99,...,97.0,98.0,98.0,98.0,98.0,98.0,98.0,98.0,97.0,97.0
2,Algeria,DTP1,96,95,96,99,99,99,99,99,...,95.0,93.0,92.0,92.0,88.0,NaN,NaN,NaN,NaN,NaN
3,Andorra,DTP1,99,99,99,99,99,96,99,99,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,DTP1,67,61,67,65,69,67,73,79,...,41.0,33.0,31.0,31.0,28.0,28.0,25.0,NaN,NaN,NaN

In [53]:
dtp1_2= pd.melt(dtp1_df,
                id_vars = ['country', 'vaccine'],
                var_name = 'year',
                value_name = 'cases')

dtp1_2.head()

       country vaccine  year  cases
0  Afghanistan    DTP1  2018   73.0
1      Albania    DTP1  2018   99.0
2      Algeria    DTP1  2018   96.0
3      Andorra    DTP1  2018   99.0
4       Angola    DTP1  2018   67.0

In [54]:
dtp1_sort = dtp1_2.sort_values(by = ['country', 'year'])

dtp1_sort.head()

          country vaccine  year  cases
7372  Afghanistan    DTP1  1980   22.0
7178  Afghanistan    DTP1  1981    NaN
6984  Afghanistan    DTP1  1982   24.0
6790  Afghanistan    DTP1  1983   24.0
6596  Afghanistan    DTP1  1984   39.0

In [55]:
dtp1_sort.to_csv('data_sets/csv/dtp1_pertussis_coverage.csv')

In [59]:
dtp1_df = pd.read_csv('data_sets/csv/dtp1_pertussis_coverage.csv')
dtp1_df.head()

       country vaccine  year  cases
0  Afghanistan    DTP1  1980   22.0
1  Afghanistan    DTP1  1981    NaN
2  Afghanistan    DTP1  1982   24.0
3  Afghanistan    DTP1  1983   24.0
4  Afghanistan    DTP1  1984   39.0

# Functions for tidying data

In [66]:
def tidy_coverage(vaccine):
    # pivots year values to its own column called year, creates coverage percentage column
    melt = pd.melt(vaccine,
                   id_vars = ['country', 'vaccine'],
                   var_name = 'year',
                   value_name = 'coverage_percentage')
    
    # sorts data by country and year
    sort = melt.sort_values(by = ['country', 'year'])
    
    return sort

def tidy_cases(vaccine):
    # pivots year values to its own column called year, creates cases column
    melt = pd.melt(vaccine,
                   id_vars = ['country', 'vaccine'],
                   var_name = 'year',
                   value_name = 'cases')
    
    # sorts data by country and year
    sort = melt.sort_values(by = ['country', 'year'])
    
    return sort

In [65]:
def tidy_data(df, value_column_name):
    """pivots year values to its own column identified by value_column_name"""
    return pd.melt(df,
                   id_vars = ['country', 'vaccine'],
                   var_name = 'year',
                   value_name = value_column_name) \
             .sort_values(by = ['country', 'year'])

# Measles Coverage

In [64]:
measles_cov = pd.read_csv('data_sets/csv/mcvi_measles_coverage.csv')

measles_cov.head()

,country,vaccine,2018,2017,2016,2015,2014,2013,2012,2011,...,1989,1988,1987,1986,1985,1984,1983,1982,1981,1980
0,Afghanistan,MCV1,64,64,64,63,60,57,59,64,...,22.0,34.0,31.0,14.0,14.0,14.0,9.0,8.0,NaN,11.0
1,Albania,MCV1,94,96,96,97,98,99,98,99,...,96.0,96.0,96.0,96.0,96.0,96.0,96.0,93.0,90.0,90.0
2,Algeria,MCV1,80,88,94,95,95,95,95,95,...,82.0,81.0,73.0,67.0,68.0,NaN,NaN,NaN,NaN,NaN
3,Andorra,MCV1,99,99,97,96,96,95,98,99,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,MCV1,50,42,45,51,56,59,65,57,...,48.0,56.0,55.0,44.0,44.0,35.0,26.0,NaN,NaN,NaN

In [65]:
measles_cov_df = tidy_coverage(measles_cov)

In [66]:
measles_cov_df.head()

          country vaccine  year  cases
7372  Afghanistan    MCV1  1980   11.0
7178  Afghanistan    MCV1  1981    NaN
6984  Afghanistan    MCV1  1982    8.0
6790  Afghanistan    MCV1  1983    9.0
6596  Afghanistan    MCV1  1984   14.0

In [67]:
measles_cov_df.to_csv('data_sets/csv/mcvi_measles_coverage.csv')

# DTP3 Coverage

In [68]:
# read in csv file
dtp3 = pd.read_csv('data_sets/csv/dtp3_pertussis_coverage.csv')

# view data header
dtp3.head()

,country,vaccine,2018,2017,2016,2015,2014,2013,2012,2011,...,1989,1988,1987,1986,1985,1984,1983,1982,1981,1980
0,Afghanistan,DTP3,66,66,66,65,62,64,67,68,...,33.0,35.0,25.0,11.0,15.0,16.0,5.0,5.0,3.0,4.0
1,Albania,DTP3,99,99,98,99,98,99,99,99,...,94.0,96.0,96.0,96.0,96.0,95.0,95.0,95.0,94.0,94.0
2,Algeria,DTP3,91,91,91,95,95,95,95,95,...,87.0,85.0,79.0,73.0,69.0,NaN,NaN,NaN,NaN,NaN
3,Andorra,DTP3,99,99,98,97,97,96,99,99,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,DTP3,59,52,55,55,55,54,52,46,...,18.0,12.0,10.0,10.0,8.0,8.0,6.0,NaN,NaN,NaN

In [70]:
dtp3_df = tidy(dtp3)

dtp3_df.head()

          country vaccine  year  cases
7372  Afghanistan    DTP3  1980    4.0
7178  Afghanistan    DTP3  1981    3.0
6984  Afghanistan    DTP3  1982    5.0
6790  Afghanistan    DTP3  1983    5.0
6596  Afghanistan    DTP3  1984   16.0

In [72]:
dtp3_df.to_csv('data_sets/csv/dtp3_pertussis_coverage.csv')

# MCV2 (Measles)

In [74]:
mcv2 = pd.read_csv('data_sets/csv/mcv2_coverage.csv')

mcv2.head()

,country,vaccine,2018,2017,2016,2015,2014,2013,2012,2011,...,2009,2008,2007,2006,2005,2004,2003,2002,2001,2000
0,Afghanistan,MCV2,39.0,39.0,39.0,39.0,39.0,35.0,33.0,31.0,...,24.0,23.0,4.0,18.0,9.0,2.0,NaN,NaN,NaN,NaN
1,Albania,MCV2,96.0,98.0,98.0,98.0,98.0,99.0,99.0,99.0,...,98.0,98.0,95.0,94.0,97.0,96.0,93.0,93.0,90.0,NaN
2,Algeria,MCV2,77.0,92.0,96.0,99.0,99.0,93.0,95.0,96.0,...,98.0,96.0,95.0,98.0,94.0,94.0,96.0,93.0,73.0,78.0
3,Andorra,MCV2,95.0,94.0,90.0,88.0,90.0,91.0,89.0,82.0,...,82.0,86.0,80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,MCV2,35.0,30.0,26.0,26.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [75]:
mcv2_df = tidy(mcv2)

mcv2_df.head()

          country vaccine  year  coverage_percentage
3492  Afghanistan    MCV2  2000                  NaN
3298  Afghanistan    MCV2  2001                  NaN
3104  Afghanistan    MCV2  2002                  NaN
2910  Afghanistan    MCV2  2003                  NaN
2716  Afghanistan    MCV2  2004                  2.0

In [81]:
dtp1

          country vaccine  year  coverage_percentage
0     Afghanistan    DTP1  1980                 22.0
1     Afghanistan    DTP1  1981                  NaN
2     Afghanistan    DTP1  1982                 24.0
3     Afghanistan    DTP1  1983                 24.0
4     Afghanistan    DTP1  1984                 39.0
...           ...     ...   ...                  ...
7561     Zimbabwe    DTP1  2014                 98.0
7562     Zimbabwe    DTP1  2015                 94.0
7563     Zimbabwe    DTP1  2016                 94.0
7564     Zimbabwe    DTP1  2017                 94.0
7565     Zimbabwe    DTP1  2018                 94.0

[7566 rows x 4 columns]

In [82]:
dtp3

          country vaccine  year  coverage_percentage
0     Afghanistan    DTP3  1980                  4.0
1     Afghanistan    DTP3  1981                  3.0
2     Afghanistan    DTP3  1982                  5.0
3     Afghanistan    DTP3  1983                  5.0
4     Afghanistan    DTP3  1984                 16.0
...           ...     ...   ...                  ...
7561     Zimbabwe    DTP3  2014                 91.0
7562     Zimbabwe    DTP3  2015                 87.0
7563     Zimbabwe    DTP3  2016                 90.0
7564     Zimbabwe    DTP3  2017                 89.0
7565     Zimbabwe    DTP3  2018                 89.0

[7566 rows x 4 columns]

In [6]:
mmr_usa_df = pd.read_csv('data_sets/csv/usa_mmr_coverage.csv')

mmr_usa_df.head()

  country  year  coverage_percentage
0     usa  1999                 91.1
1     usa  2000                 90.0
2     usa  2001                 91.1
3     usa  2002                 91.6
4     usa  2003                 93.0

In [8]:
row_concat = pd.concat([mmr, mmr_usa_df])

row_concat.head()

C:\Users\anjel\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

  continent  country  coverage_percentage vaccine  year
0      Asia  Armenia                 84.0     MMR  1991
1      Asia  Armenia                 84.0     MMR  1992
2      Asia  Armenia                 81.0     MMR  1993
3      Asia  Armenia                 78.0     MMR  1994
4      Asia  Armenia                  5.0     MMR  1995

In [11]:
row_concat.to_csv('data_sets/csv/concat.csv')

In [19]:
mmr = pd.read_csv('data_sets/csv/mmr_coverage.csv')
                  
mmr.head()

   country vaccine  year  coverage_percentage
0  Armenia     MMR  1991                 84.0
1  Armenia     MMR  1992                 84.0
2  Armenia     MMR  1993                 81.0
3  Armenia     MMR  1994                 78.0
4  Armenia     MMR  1995                  5.0

In [21]:
sort_mmr = mmr.sort_values(by = ['country', 'year'])

sort_mmr.head()

   country vaccine  year  coverage_percentage
0  Armenia     MMR  1991                 84.0
1  Armenia     MMR  1992                 84.0
2  Armenia     MMR  1993                 81.0
3  Armenia     MMR  1994                 78.0
4  Armenia     MMR  1995                  5.0

In [22]:
sort_mmr.to_csv('data_sets/csv/mmr_coverage.csv')

# Merge Vaccine_coverage into one dataframe

In [12]:
dtp1 = pd.read_csv('datasets/csv/vaccine_coverages/dtp1_coverage.csv')
dtp3 = pd.read_csv('datasets/csv/vaccine_coverages/dtp3_coverage.csv')

mcv1 = pd.read_csv('datasets/csv/vaccine_coverages/mcv1_coverage.csv')
mcv2 = pd.read_csv('datasets/csv/vaccine_coverages/mcv2_coverage.csv')

mmr = pd.read_csv('datasets/csv/vaccine_coverages/mmr_coverage.csv')

In [24]:
merge_vaccines = pd.concat([dtp1, dtp3, mcv1, mcv2, mmr], sort = False) \
                   .sort_values(by = ['country', 'year']) \
                   .reset_index(drop = True)

<bound method DataFrame.notna of            country vaccine  year  coverage_percentage
0      Afghanistan    DTP1  1980                 22.0
1      Afghanistan    DTP3  1980                  4.0
2      Afghanistan    MCV1  1980                 11.0
3      Afghanistan    DTP1  1981                  NaN
4      Afghanistan    DTP3  1981                  3.0
...            ...     ...   ...                  ...
26509     Zimbabwe    MCV2  2017                 78.0
26510     Zimbabwe    DTP1  2018                 94.0
26511     Zimbabwe    DTP3  2018                 89.0
26512     Zimbabwe    MCV1  2018                 88.0
26513     Zimbabwe    MCV2  2018                 78.0

[26514 rows x 4 columns]>

In [26]:
vaccine_coverage = pd.read_csv('datasets/csv/vaccine_coverages/merge_vaccines_cleaned.csv')\

vaccine_coverage

In [29]:
vaccine_coverage.set_index(["country", "year"]).count(level="country")

C:\Users\anjel\Anaconda3\lib\site-packages\beakerx\tabledisplay\tabledisplay.py:114: FutureWarning: The 'get_values' method is deprecated and will be removed in a future version. Use '.to_numpy()' or '.array' instead.
  index_values = args[0].index.get_values()[index]

In [16]:
merge_vaccines.to_csv('datasets/csv/vaccine_coverages/merge_vaccines.csv')

# Merging Incidence Cases

In [70]:
measles = pd.read_csv('data_sets/csv/measles_cases.csv').dropna()
mumps = pd.read_csv('data_sets/csv/mumps_cases.csv').dropna()
pertussis = pd.read_csv('data_sets/csv/pertussis_cases.csv').dropna()

In [71]:
merge_incidence_cases = pd.concat([measles, mumps, pertussis], sort = False) \
                   .sort_values(by = ['country', 'year']) \
                   .reset_index(drop = True)

merge_incidence_cases.head()

       country    disease  year    cases
0  Afghanistan    measles  1980  32455.0
1  Afghanistan  pertussis  1980  15748.0
2  Afghanistan    measles  1981  31107.0
3  Afghanistan  pertussis  1981  15388.0
4  Afghanistan    measles  1982  20320.0

In [72]:
merge_incidence_cases.to_csv('data_sets/csv/all_disease_incidences.csv')

# Merge Incidence Cases & Population

In [3]:
cases = pd.read_csv('datasets/csv/all_disease_incidences.csv')

cases

           country    disease  year  cases
0      Afghanistan    measles  1980  32455
1      Afghanistan  pertussis  1980  15748
2      Afghanistan    measles  1981  31107
3      Afghanistan  pertussis  1981  15388
4      Afghanistan    measles  1982  20320
...            ...        ...   ...    ...
15250     Zimbabwe  pertussis  2016      3
15251     Zimbabwe    measles  2017      1
15252     Zimbabwe  pertussis  2017      0
15253     Zimbabwe    measles  2018      1
15254     Zimbabwe  pertussis  2018      0

[15255 rows x 4 columns]

In [5]:
tot_pop = pd.read_csv('datasets/csv/tot_pop_per_country.csv')

tot_pop.head()

       country  year  population
0  Afghanistan  1980    13356511
1  Afghanistan  1981    13171673
2  Afghanistan  1982    12882528
3  Afghanistan  1983    12537730
4  Afghanistan  1984    12204292

In [6]:
merge_cases_pop = pd.concat([cases, tot_pop], sort = False) \
                   .sort_values(by = ['country', 'year']) \
                   .reset_index(drop = True)

merge_cases_pop.head()

       country    disease  year    cases  population
0  Afghanistan    measles  1980  32455.0         NaN
1  Afghanistan  pertussis  1980  15748.0         NaN
2  Afghanistan        NaN  1980      NaN  13356511.0
3  Afghanistan    measles  1981  31107.0         NaN
4  Afghanistan  pertussis  1981  15388.0         NaN